Documentation/In-depth/TheInstallTool/Index.rst

Do no longer provide examples where TYPO3_CONF_VARS is accessed without
$GLOBALS prefix.
Accordingly to #15 of security guide.

TASK: Always use GLOBALS['TYPO3_CONF_VARS']

---

Documentation/Upgrade/InstallTheNewSource/Index.rst

Provide a special hint for updates to 8.x with changed database
connection configuration.
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/20, https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/issues/24

TASK: Mention to check out the breaking changes

---

Documentation/MigrateToComposer/MigrationSteps.rst

Extensions are located in `typo3conf/ext/`, not `typo3conf/`. Therefore the correct path in the documentation should read `public/typo3conf/ext/my_sitepackage`.

[BUGFIX] Correct path to extensions

---

Documentation/Upgrade/Preparation/Index.rst

Wording about TYPO3's deprecation strategy updated as discussed in Slack (channel `#typo3-documentation`).

TYPO3 Deprecation Strategy updated

---

Documentation/In-depth/SystemRequirements/Index.rst

Add to the requirements that the minimum GraphigsMagick version that should be used is 1.3; see the issue https://forge.typo3.org/issues/84841

specify GraphicsMagick version required

---

Documentation/QuickInstall/Composer/Index.rst
Documentation/QuickInstall/GetAndUnpack/Index.rst
Documentation/QuickInstall/Index.rst

Add manual installation on same menu level as composer,
not as subchapter of composer.
Add additial notes for clarification.
Fix link.
Resolves: #51

[BUGFIX] Fix menu hierarchy in Quickstart

---

Documentation/In-depth/Distributions/Index.rst
Documentation/In-depth/SystemRequirements/Index.rst
Documentation/In-depth/ThePackageInDetail/Index.rst
Documentation/In-depth/WhichPackageAndFormat/Index.rst
Documentation/Introduction/Index.rst
Documentation/MigrateToComposer/BestPractices.rst
Documentation/MigrateToComposer/Index.rst
Documentation/MigrateToComposer/MigrationSteps.rst
Documentation/MigrateToComposer/Requirements.rst
Documentation/QuickInstall/Composer/Index.rst
Documentation/QuickInstall/GetAndUnpack/Index.rst

- apply title case (capitalize most words as defined in TYPO3 Content Style Guide)
- use spelling 'Composer' unless explicitly referring to command 'composer'.
In the latter case use inline code (backticks).

Language corrections

---

Documentation/Index.rst

- Since a sitemap is already on the start page, people had to page
through 2 sitemaps
- In general, we move sitemap to the end

Move sitemap to the end

---

Documentation/Composer/Index.rst
Documentation/Index.rst
Documentation/MigrateToComposer/BestPractices.rst

Some of the "best practices" in the chapter for migrating to Composer may be
generally helpful, not just for people migrating to Composer. However, currently
they are a bit hidden.
For this reason, a new chapter "Working With Composer" is created and the text
moved there

Move best practices to general Composer chapter

---

Documentation/QuickInstall/Composer/Index.rst

Just a rather small change! I wanted to merge together content from the Wiki page handling the same topic (https://wiki.typo3.org/ComposerInstallation), so we can just provide a link to the docs version to clear some _duplicated_ content.
And I think the official TYPO3 video on the subject is a fair inclusion.

Add official TYPO3 video tutorial link to composer installation guide

---

Documentation/In-depth/SystemRequirements/Index.rst

Mention TYPO3 v10 instead of v9.
On Mac, php 7.3 causes troubles because prce. In order to help users to save some headaches, this problem is mentioned here already.

Fix TYPO3 version; add warning for mac users

---

Documentation/QuickInstall/Composer/Index.rst

- Reduce the number of notes: There were 4 admonitions (note, important)
on the page. Reducing this makes the page easier readable
- Some of the things pointed out were only relevant for command with
version constraints including asterix or caret which are not even
used on this page (we can use this note on the lower version pages)
- Slighly reorder text on page

Clean up quick install with Composer page

---

Documentation/MigrateToComposer/MigrationSteps.rst

If this step is not done from a created project, you will get error #1278450972. You must run `composer dumpautoload` for the project to run with the extensions you are keeping in the ext directory

add aditional step to migrating to composer

---

Documentation/Composer/Index.rst

You get a better overview of installed extensions and the core
if you don't see required packages by TYPO3 core or 3rd-party
TYPO3 extensions.

Add info about composer outdated command with direct option

---

Documentation/Introduction/Index.rst

We should not link to specific content elements by their UID since they are bound to change over time.
Discovered in https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Editors/pull/21

[TASK] Drop CE anchor

---

Documentation/In-depth/WhichPackageAndFormat/Index.rst

- Add Composer to title. The title "Which Package and which format" was used in older
versions of this manual, when there are several packages - currently this
is no longer relevant. Having Composer in the title fits better with the
content
- Add headers to separate the parts about with Composer from without Composer
- We already have a page for installing without Composer. Link to that

Clarify chapter "Which package and which format"

---

Documentation/In-depth/SystemRequirements/Index.rst

Added information on IIS config: in order to use speaking url, the url-rewrite plugin should be already present on IIS - see the issue https://forge.typo3.org/issues/92058
Please review.

Update documentation about IIS config

---

Documentation/QuickInstall/Index.rst

Before the change, we had 3 subchapters listed on start page, without
much context or explanation:
* Install with composer
* Install without composer
* Install tool
The first 2 points are mutually exclusive, the third point must be
executed in any case.
This change tries to give the user a better overview of the various
installation steps.

Give overview over installation steps in quick install

---

Documentation/Settings.cfg
Documentation/Upgrade/ChangelogAndNewsmd/Index.rst
Documentation/Upgrade/Preparation/Index.rst

- Merge page about changelogs to preparation page because this should be done
before updating (it even says "Before upgrading you should at least take a
look at the sections ..."). The "Preparation" page contains information about
what to do before updating. More importantly, it already contains related
information like information on extension scanner and deprecations.
- Rename the page "Preparation" to "Before Upgrading" because that is
clearer.
- Add some links (e.g. to extension scanner page)
- Add the 3 methods to read changelogs with their individual advantages.
Related: #142

Improve Upgrade preparation page

---

Documentation/QuickInstall/Composer/Index.rst

When using the command I got the error: "zsh: no matches found: typo3/cms-base-distribution:^9". I think it is safer to have the version constraint inside quotes.

Fix error at composer command

---

Documentation/MigrateToComposer/MigrationSteps.rst

This option no longer has any effect. Remove in examples and add note.
Resolves: #159

Remove cms-package-dir

---

Documentation/MigrateToComposer/MigrationSteps.rst

There is an old comment left, which mentions 7.* in context of version examples with TYPO3 9

Update outdated 7.* to 9.* in version examples

---

Documentation/QuickInstall/Index.rst

DDEV is already mentioned on the subpage: https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/Composer/Index.html#install-via-composer
> To create a new TYPO3 project using the TYPO3 Base Distribution in a ddev environment:
> # Download the Base Distribution, the latest "LTS" release (10)
> ddev composer create "typo3/cms-base-distribution:^10" --prefer-dist

Add DDEV to quick installation

---

Documentation/In-depth/Index.rst
Documentation/QuickInstall/Index.rst

- "Quick installation" -> "Installation steps"
- "In-Depth installation" -> "Installation explained"
This makes it more clearer to me why there are 2 chapters. At the beginning I had expected to find a short walkthrough in "Quick installation" and a longer more detailed walkthrough in "In-Depth". But, "In-Depth" is not really a walkthrough at all. You should start with the Installation steps in any case. "In depth" just contains some further explanations. 
I hope, this change makes this more clear.

Rename installation chapters

---

Documentation/QuickInstall/GetAndUnpack/Index.rst

By default, "public" is used in Composer installations. The page
about installing TYPO3 without Composer uses "htdocs". By
changing this to "public", we already have a directory structure
that is more consistent with the one used in Composer installations.
This might make it a little more easier to migrate later.
Also, this is more consistent with the rest of the guide which uses
"public".
Resolves: #178

Use consistent naming for public directory

---

Documentation/MigrateToComposer/MigrationSteps.rst

In the chapter "Migrate TYPO3 Project to Composer"
it is described how to create a project composer.json
This did not include some essentials in order to regenerated
PackageStates.php.
A "script" section is added and information about typo3_console
and base distribution are added.

Add essential information to composer.json

---

Documentation/Upgrade/UpdateReferenceIndex/Index.rst

Added a tip on how to suppress the output of the symfony console progressbar when executed in CLI context
Releases: master, 10.4

Add tip for referenceindex:update command

---

Documentation/MigrateToComposer/BestPractices.rst

add a reference to "Extension Development Manual" instead of composer.typo3.org

replace reverence to composer.typo3.org

---

Documentation/In-depth/SystemRequirements/Index.rst

See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93048-BackendURLRewrites.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082

[TASK] Add Backend URL Nginx rules

---

Documentation/Troubleshooting/Index.rst

Backport 10.4, 9.5
http://wiki.typo3.org/FAQ/Reset_admin_password
refs: https://github.com/TYPO3-Documentation/T3DocTeam/issues/154

Wiki Migration: Reset_admin_password

---

Documentation/Upgrade/ChangelogAndNewsmd/Index.rst
Documentation/Upgrade/Index.rst

The page ChangelogAndNewsmd/Index.rst was orphaned but not removed
from the menu.
Remove from menu and remove the text on the page (except for the
information that the content was moved).
Releases: master, 10.4

Remove "Check the changelog" from the menu

---

Documentation/In-depth/TheInstallTool/Index.rst

I could never find a way where the .htaccess file is shipped in TYPO3 10.

Add hint to generate the .htaccess file.

---

Documentation/Upgrade/Index.rst

The upgrade wizard part should be done directly after updating the source.
Otherwise there may be problems (for example in 10.4, where entering the
backend before database schema transformations will render the backend
unusable).
Converting the extensions can be done before the upgrade process.
Resolves: #201

[BUGFIX] Change order for convert global extensions

---

Documentation/In-depth/ComposerJson/Index.rst
Documentation/In-depth/Index.rst

Add an example composer.json file for a project to refer to.

Add sample project composer.json

---

Documentation/Composer/Index.rst

https://docs.typo3.org/m/typo3/guide-installation/master/en-us/Composer/Index.html#run-composer-locally contained an example with "7.2" only which is not recommended and should have been "7.2.32" for example. 
Since the upstream documentation contains an interesting note with implications on deployment, I chose to rather link it.

[BUGFIX] composer's `platform.php` should be given as whole version

---

Documentation/In-depth/SystemRequirements/Index.rst
Documentation/Settings.cfg

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395

[FEATURE] #93631 - Support for PHP 8.0

---

Documentation/In-depth/TheInstallTool/Index.rst

There is a case when no TYPO3 backend login is possible.
See TYPO3 slack typo3-cms from 1st July 2021.

TYPO3  backend login

---

Documentation/QuickInstall/Composer/Index.rst

Without the version tag composer will get typo3 v11 instead of 10

Added version to composer instruction

---

Documentation/In-depth/SystemRequirements/Index.rst

The LOCK TABLE is not a requirement of the core and will be removed
from the PermissionChecker with this patch:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70738
The documentation should also not mention this as a requirement.

[TASK] Remove "LOCK TABLE" from the permission requirements

---

Documentation/In-depth/OpcodeCache/Index.rst

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-94665-WincacheCacheBackend.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

Deprecation: #94665 - Wincache cache backend

---

Documentation/Index.rst
Documentation/Tools/Index.rst

This commit adds a new section to the Upgrade Guide
titled "third party tools".
The first being TYPO3 Rector.
[+] Add "Third-party Tools" section with card
[+] Add information about T3 Rector
Resolves #208

[TASK] Add third-party tools chapter with information on Rector

---

Documentation/Minor/Index.rst

Documentation should always suggest the long form of CLI options since they are usually self-explaining.

Avoid short form for --with-all-dependencies

---

Documentation/MigrateToComposer/CoWorking.rst

This is taken from https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/v11.5.1/.gitignore which does the same

Ignore /var/ folder in .gitignore

---

Documentation/Major/UpgradeCore.rst

1. The major core upgrade guide mentions to just do `composer req` on the core packages, which will fail in most cases, as there will be extensions blocking this, thus it should be mentioned how to cope with this error by just adapting the command. 
2. Additionally the `-W` parameter would make sense to make updates more robust. 
3. Additionally the example cmd show use line-continuation at the line ends to allow copy and paste

Major core upgrade needs info about other ext

---

Documentation/MigrateToComposer/MigrationSteps.rst

This has been the practice since TYPO3 9.5 so the old hint can be removed for version 12 and 11
Releases: main, 11.5
Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/issues/287

Remove hint to subtree split

---

Documentation/MigrateToComposer/MigrationSteps.rst

A user should read the introductory documents before starting migrating to a Composer installation, if they are not familiar with it.
Releases: main, 11.5, 10.4

[TASK] Link Composer introductory documents

---

Documentation/Major/PreupgradeTasks/Index.rst

This is wrong only in 11.5 branch.
Releases: 11.5

[BUGFIX] Include correct section for "Convert global extensions"

---

Documentation/MigrateToComposer/VersionControl.rst

With the mandatory usage of typo3/cms-composer-installers v5 in TYPO3 v12 the typo3conf folder is gone.
Releases: main, 12.4

[TASK] Remove typo3conf folder from .gitignore suggestion

---

Documentation/Major/PreupgradeTasks/ReferenceIndex.rst.txt

Updated the location of the "Manage Reference Index" in the TYPO3 backend. Unless I'm mistaken, in my version it's located in "System > DB Check".

Corrects backend module path for "DB Check" (#344)

---

Documentation/ApplyingCorePatches/Index.rst

./Documentation/ApplyingCorePatches/Index.rst:107: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 4 supplied.
.. code-block:: none
Example error message
Could not apply patch! Skipping. The error was: Cannot apply patch patches/Bug-98106.diff
Releases: main, 12.4, 11.5

[BUGFIX] Remove rendering warning

---

Documentation/Major/UpgradeCore.rst

Additionally:
- Spelling of "core" is adjusted ("Core")
- Language of code-block is defined explicitly
Releases: main, 12.4

[TASK] Update TYPO3 versions in "Upgrade Core" chapter

---

Documentation/Major/UpgradeCore.rst

Additionally, add a note.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/191
Releases: 12.4

[BUGFIX] Remove typo3/cms-recordlist from update command

---

Documentation/Major/UpgradeCore.rst
Documentation/Minor/Index.rst
Documentation/UpgradingExtensions/Index.rst

This should improve the output for BASH.
I want to add more files if you agree to this change.

use bash inline command

---

Documentation/MigrateToComposer/AssetMigration.rst

[BUGFIX] Remove duplicate "command" word

---

Documentation/ApplyingCorePatches/Index.rst

Add note to use `composer-exit-on-patch-failure` to get notice about an error on patching.

[DOCS] Improve docs on using composer patch

---

Documentation/ApplyingCorePatches/Index.rst

Add note to use `composer-exit-on-patch-failure` to get notice about an error on patching.
Preport of https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/pull/401

[PREPORT][DOCS] Improve docs on using composer patch (#401)
