Documentation/Upgrade/Index.rst
I've added two links to walkthroughs about 6.2 upgrade, one by myself
=> Added Links

Documentation/QuickInstall/GetAndUnpack/Index.rst
The extraction won't contain the `x` in the file as proposed
=> Adds note for the extraction of the source file

Documentation/MigrateToComposer/BestPractices.rst, Documentation/MigrateToComposer/CoWorking.rst, Documentation/MigrateToComposer/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst, Documentation/MigrateToComposer/Requirements.rst
* Fixed images
* Moved "Requirements" to own page
* Corrected some typos
=> Refactor composer tutorial

Documentation/Introduction/Index.rst, Documentation/QuickInstall/GetAndUnpack/Index.rst, Documentation/Troubleshooting/Apache/Index.rst, Documentation/Troubleshooting/Mysql/Index.rst, Documentation/Troubleshooting/Php/Index.rst, Documentation/Troubleshooting/Typo3Specific/Index.rst
This commit contains minor changes to the wording of certain paragraphs. It's aim is to make the documentation easier to read.
=> Improve general wording of documentation

Documentation/MigrateToComposer/BestPractices.rst
Change to `--with-all-dependencies`
=> Update composer parameter

Documentation/In-depth/SystemRequirements/Index.rst
since there are less troubles configuring TYPO3 image
processing possibilities with GM.
=> [TASK] Add info about preferring GM instead of IM

Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/MigrateToComposer/Index.rst
- add "TYPO3 community"
- add link to credits
- update credits
=> Add "community" to authors on start page

Documentation/In-depth/SystemRequirements/Index.rst
https://typo3.org/cms/roadmap/
=> Updated PHP version to roadmap

Documentation/In-depth/SystemRequirements/Index.rst
See https://get.typo3.org/version/9
=> Updated MySQL versions to respect the same as on get.typo3.org

Documentation/Troubleshooting/Index.rst
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/88
=> Merge Troubleshooting into one file

Documentation/Index.rst, Documentation/ReleaseIntegrity/Index.rst
imported from https://github.com/TYPO3incubator/TYPO3.Guide.Infrastructure
=> [TASK] Integrate TYPO3 release integrity guide

Documentation/Upgrade/UseTheUpgradeWizard/Index.rst
… for non Composer installations
TYPO3 v9 & v10
=> [TASK] Add information about how to run upgrade wizards from commandline

Documentation/In-depth/SystemRequirements/Index.rst
Add how to configure webserver (Apache, IIS, Nginx) for a TYPO3 installation in the system requirements section.
=> [TASK] Add how to configure webserver (Apache, IIS, Nginx)

Documentation/In-depth/Distributions/Index.rst
Updated the cms-introduction version so it fits to Typo3 v.9
=> Updated introduction version

Documentation/Includes.txt, Documentation/Upgrade/UseTheUpgradeWizard/Index.rst
Add missing slash for correct path from current web directory
refs #76
=> [BUGFIX] Path to run upgrade wizards from command line for non Composer

Documentation/Includes.txt, Documentation/Upgrade/UseTheUpgradeWizard/Index.rst
=> [TASK] Add information about how to run upgrade wizards from commandline for non Composer installations

Documentation/Troubleshooting/Index.rst
- change some text referring to install tool because the naming of
the sections has changed
- add information about config.contentObjectExceptionHandler
- add information about log files
=> Add information about error messages and logging

Documentation/In-depth/SystemRequirements/Index.rst, Documentation/Troubleshooting/Index.rst
Also,
- add some links
- add additional information
Releases: master, 9.5, 8.7
=> Add more Apache modules to system requirements

Documentation/In-depth/SystemRequirements/Index.rst, Documentation/Includes.txt, Documentation/Troubleshooting/Index.rst, Documentation/Upgrade/UseTheUpgradeWizard/Index.rst
Add more modules to system requirements
Also,
- add some links
- add additional information
Releases: master, 9.5, 8.7
=> Add more Apache modules to system requirements (9.5)

Documentation/In-depth/SystemRequirements/Index.rst
- change MySQL version contraints to comply with get.typo3.org
- add PHP upper version constraints
- group information about webserver together
- set main topic in list in bold, to enable easier skimming of
page for relevant information
- set all information at top in list - otherwise information
about image processing is easily missed
- add links on top to detail sections
=> Update System Requirements

Documentation/In-depth/SystemRequirements/Index.rst, Documentation/In-depth/WhichPackageAndFormat/Index.rst, Documentation/Upgrade/Index.rst
=> Link to version 10 of get.typo3.org

Documentation/Upgrade/InstallTheNewSource/Index.rst
This is imporant enough to warrant its own spot even without knowing about the subtree split details.
=> Separate Composer Helper tip

Documentation/QuickInstall/Index.rst
=> Split up prerequisites and toc in quick install

Documentation/QuickInstall/Composer/Index.rst
How to install TYPO3 10 LTS in a ddev environment.
=> Add information about installing in a ddev environment

Documentation/In-depth/TheInstallTool/Index.rst, Documentation/QuickInstall/Composer/Index.rst
Remove additional indents which result in blockquotes
=> Remove blockquotes

Documentation/QuickInstall/Composer/Index.rst
New lines must be inserted before and after a list. Otherwise all list items are rendered on one line.
=> Fix formatting

Documentation/Composer/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst
=> Remove information from before subtree split

Documentation/In-depth/SystemRequirements/Index.rst
It's either "a great number of" or "many" - feel free to adjust.
=> Fix sentence

Documentation/Upgrade/InstallTheNewSource/Index.rst
=> Hint for abandoned core extensions (#173)

Documentation/Upgrade/Preparation/Index.rst
=> Correct information about TYPO3 versions in "Handling Deprecations"

Documentation/Troubleshooting/Index.rst
See Deprecation 88366
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
=> [TASK] Rename cache identifiers

Documentation/Upgrade/UseTheUpgradeWizard/Index.rst
=> Update some GUI labels for install tool page

Documentation/Composer/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst
Add information about files that should be moved and changed
file locations to the "Migrate to Composer" chapter.
Resolves: #182
=> Add information about moving files

Documentation/Upgrade/Backup/Index.rst
=> [TASK] Add cross-link to TYPO3 Explained on backups

Documentation/In-depth/SystemRequirements/Index.rst
Releases: master, 10.4
This patch should get merged once https://review.typo3.org/c/Packages/TYPO3.CMS/+/67471 is merged.
=> [BUGFIX] Fix requirement for ext:mbstring

Documentation/Historicallnformation/BreakingChangesExtbase6.rst, Documentation/Historicallnformation/Index.rst, Documentation/Index.rst
http://wiki.typo3.org/Breaking_Changes
refs: https://github.com/TYPO3-Documentation/T3DocTeam/issues/154
=> Wiki Migration: Breaking Changes

Documentation/In-depth/OpcodeCache/Index.rst, Documentation/Troubleshooting/Index.rst
https://wiki.typo3.org/Opcode_Cache
refs: https://github.com/TYPO3-Documentation/T3DocTeam/issues/154
=> Wiki Migration: Import Export

Documentation/Upgrade/InstallTheNewSource/Index.rst
=> Index of InstallTheNewSource fixed up

Documentation/QuickInstall/TheInstallTool/Index.rst
=> The Admin Tool is also called Install Tool

Documentation/In-depth/SystemRequirements/Index.rst
Do not backport, only valid for master.
=> Fix link and indention

Documentation/In-depth/TheInstallTool/Index.rst
One in the backend and one in the frontend.
=> 2 forms of admin tool now exist

Documentation/HistoricalInformation/BreakingChangesExtbase6.rst
The main repository for TYPO3 changed, update the documentation accordingly.
=> [TASK] Update repository URL

Documentation/Composer/Index.rst, Documentation/In-depth/SystemRequirements/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.
=> [TASK] Update TYPO3 repository URL

Documentation/Composer/Index.rst, Documentation/ExtensionInstallation/Index.rst, Documentation/In-depth/ComposerJson/Index.rst, Documentation/In-depth/ThePackageInDetail/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
See Core Feature 94996
=> [FEATURE] Add setup command to extension installation

Documentation/MigrateContent/Index.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-84718-AddCLIExportCommandToImpExpExtension.html
=> [Feature] #84718 - Add CLI export command to EXT:impexp

Documentation/Major/PostupgradeTasks/UpgradeWizard.rst.txt
See TYPO3-Documentation/T3DocTeam#164 for details.
=> [TASK] Disable all dummy urls with `:samp:`

Documentation/MigrateToComposer/MigrationSteps.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Important-95647-ComposerInstallationsAndExtensionUsage.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
releases: master, 11.5
=> Important: #95647 - Composer installations and extension usage

Documentation/Major/PostupgradeTasks/UpgradeWizard.rst.txt
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Unify top-level domain of dummy urls

.editorconfig, Documentation/.editorconfig, Documentation/Legacy/Index.rst, Documentation/MigrateToComposer/MigrationSteps.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

Documentation/Major/PostupgradeTasks/BackendTranslations.rst.txt
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/170
releases: main, 11.5, 10.4, 9.5, 8.7, 7.6
=> [TASK] Remove old wiki links

Documentation/Legacy/Index.rst, Documentation/Major/PreupgradeTasks/ReferenceIndex.rst.txt, Documentation/MigrateContent/Index.rst, Documentation/MigrateToComposer/BestPractices.rst, Documentation/MigrateToComposer/CoWorking.rst, Documentation/MigrateToComposer/MigrationSteps.rst, Documentation/MigrateToComposer/Requirements.rst
to make it more clear where code should go
Releases: main, 11.5
=> [TASK] Add captions to code-blocks (#94)

Documentation/Minor/Index.rst
=> Add "-m" option to "composer outdated ..."

Documentation/MigrateToComposer/MigrationSteps.rst
=> [TASK] Adjust base distribution link

Documentation/MigrateToComposer/Requirements.rst
=> [Backpüort 10.4] [TASK] Revise requirements of Composer migration chapter (#317)

Documentation/MigrateToComposer/MigrationSteps.rst
=> [Backport 10.4] [TASK] Link Composer introductory documents (#330)

Documentation/Major/PreupgradeTasks/ReferenceIndex.rst.txt, Documentation/Settings.cfg
=> [TASK] Revise the "Update reference index" section

Documentation/Major/PreupgradeTasks/ReferenceIndex.rst.txt, Documentation/Settings.cfg
=> [Backport 11.5] [TASK] Revise the "Update reference index" section (#334)

Documentation/Major/PostupgradeTasks/ClearCaches.rst.txt
This is a preparation for adding the CLI command for flushing the cache in v11 and v12.
Releases: main, 11.5, 10.4
=> [TASK] Revise the "Clear cache" section

Documentation/Major/PostupgradeTasks/ClearCaches.rst.txt
This is a preparation for adding the CLI command for flushing the cache in v11 and v12.
Releases: main, 11.5
=> [Backport 11.5] [TASK] Revise the "Clear cache" section (#335)

Documentation/Index.rst, Documentation/Minor/Index.rst
=> [TASK] Use "update" over "upgrade" for patch updates

.github/workflows/backport.yml
=> [CI] Update backport library

Documentation/QuickInstall/Composer/Index.rst
Resolves: #350
Releases: 10.4, 9.5
=> [TASK] Remove reference to private YouTube video

Documentation/QuickInstall/Composer/Index.rst
Resolves: #350
Releases: 10.4, 9.5
=> [TASK] Remove reference to private YouTube video (#351)

.gitignore, composer.json
Additionally, ignore composer.lock file and vendor folder.
Releases: main, 12.4
=> [TASK] Update TYPO3 version

Documentation/MigrateToComposer/MigrationSteps.rst
=> [BUGFIX] Correct path to backup include in migration chapter

Documentation/Major/UpgradeCore.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/734
Releases: main
=> [TASK] Mention t3editor was merged into backend

Documentation/Major/Index.rst, Documentation/Major/PostupgradeTasks/BackendTranslations.rst.txt, Documentation/Major/PostupgradeTasks/ClearCaches.rst.txt, Documentation/Major/PostupgradeTasks/DatabaseAnalyser.rst.txt, Documentation/Major/PostupgradeTasks/Index.rst, Documentation/Major/PostupgradeTasks/UpgradeWizard.rst.txt, Documentation/Major/PostupgradeTasks/UserSettings.rst.txt, Documentation/Major/PreupgradeTasks/Backup.rst.txt, Documentation/Major/PreupgradeTasks/Changelog.rst.txt, Documentation/Major/PreupgradeTasks/Deprecations.rst.txt, Documentation/Major/UpgradeCore.rst
Additionally, streamline some spellings.
Releases: main, 12.4
=> [TASK] Adjust indentations in "Major upgrade" chapter

Documentation/Major/PreupgradeTasks/ConvertGlobalExtensions.rst.txt
* The files are not deleted in the Backend Module.
* Update Documentation/Major/PreupgradeTasks/ConvertGlobalExtensions.rst.txt
---------
=> [BACKPORT] Backport pr 354

Documentation/Tools/Index.rst
References #273
I'm a bit unsure if we really want to add this due to the forking/maintenance nature, but on the other hand it could be helpful.
=> [TASK] Add section on core upgrader

Documentation/Major/PostupgradeTasks/Index.rst
=> [TASK] Mention core-upgrader

Documentation/Minor/Index.rst
I could not find a phrase "to action a task" .
=> replace "to action"

Documentation/Includes.rst.txt
=> [TASK] Add end of life hint and remove unused content from Includes.rst.txt
